class traduccion:
    def __init__(self):
        self.translations = {
            # Español
            "es": {
                # Home / Login / Registro
                "home_title": "Bienvenido a Ecorisk",
                "home_subtitle": "La plataforma perfecta para evaluar, reportar y gestionar riesgos ambientales.",
                "login_title": "Iniciar Sesión",
                "login_user": "Usuario",
                "login_pass": "Contraseña",
                "login_button": "Entrar",
                "register_link": "Registrarse",
                "Without_account": "¿No tienes cuenta?",
                "register_title": "Registro de Usuario",
                "register_user": "Nombre de Usuario",
                "register_email": "Correo Electrónico",
                "register_pass": "Contraseña",
                "register_button": "Registrarse",
                "login_link": "Iniciar Sesión",
                "user_type_label": "Tipo de usuario",
                "user_type_select": "Seleccione...",
                "user_type_admin": "Administrador",
                "user_type_authority": "Autoridad Ambiental",
                "user_type_common": "Usuario Común",
                "menu_title": "Menú Principal",
                "menu_subtitle": "Elige una opción para comenzar:",
                "impactos": "Impactos Ambientales",
                "problemas": "Problemas Ambientales",
                "tickets": "Tickets",
                "usuarios": "Usuarios",
                "config": "Configuración",
                "footer_quote": "Reporto el riesgo, el futuro no arriesgo",
                
                # Formulario Reporte Ambiental
                "register_report_title": "Reporte Ambiental",
                "register_report_subtitle": "Ayúdanos a proteger el medio ambiente",
                "location_section": "Localización",
                "localidad_label": "Localidad",
                "barrio_label": "Barrio",
                "search_placeholder": "Escriba para buscar...",
                "select_placeholder": "Seleccione...",
                "impact_section": "Detalles del Impacto",
                "categoria_label": "Categoría ambiental",
                "impacto_label": "Impacto ambiental",
                "descripcion_label": "Descripción",
                "evidencia_section": "Evidencia",
                "upload_placeholder": "Arrastre su imagen aquí o haga clic para seleccionar",
                "upload_optional": "Opcional",
                "register_report_button": "Registrar Ticket"  ,
                "cancel_button": "Cancelar",
                
                # Dashboards
                "dashboard_admin_title": "Panel del Administrador",
                "dashboard_admin_subtitle": "Desde aquí puedes gestionar usuarios, revisar reportes y supervisar el sistema EcoRisk.",
                "dashboard_admin_button1": "Ver Impactos Ambientales",
                "dashboard_admin_button3": "Ver Reportes",
                "dashboard_authority_title": "Panel de la Autoridad Ambiental",
                "dashboard_authority_subtitle": "Consulta reportes ciudadanos, analiza impactos y emite resoluciones ambientales.",
                "dashboard_authority_button1": "Ver Impactos Ambientales",
                "dashboard_authority_button2": "Revisar Reportes",
                "dashboard_authority_button3": "Emitir Resoluciones",
                "dashboard_greeting": "Hola,",
                "descripcion_admin": "Aquí puedes gestionar usuarios, revisar reportes y administrar configuraciones del sistema.",
                "descripcion_autoridad": "Aquí puedes revisar reportes ciudadanos, analizar impactos ambientales y emitir resoluciones.",
                
                # Modal Ver Reportes
                "ticket_id": "ID Ticket",
                "ticket_descripcion": "Descripción",
                "ticket_fecha": "Fecha Creación",
                "ticket_categoria": "Categoría",
                "ticket_severidad": "Severidad",
                "ticket_estado": "Estado",
                "ticket_localidad": "Localidad",
                "ticket_impacto": "Impacto",
                "ticket_persona": "Persona",
                "ticket_estado_tickets": "Estado Tickets",
                "close_button": "Cerrar",
            },

            # Inglés
            "en": {
                "home_title": "Welcome to Ecorisk",
                "home_subtitle": "The perfect platform to evaluate, report, and manage environmental risks.",
                "login_title": "Login",
                "login_user": "Username",
                "login_pass": "Password",
                "login_button": "Sign In",
                "register_link": "Register",
                "Without_account": "Don't you have an account?",
                "register_title": "User Registration",
                "register_user": "Username",
                "register_email": "Email",
                "register_pass": "Password",
                "register_button": "Register",
                "login_link": "Login",
                "user_type_label": "User Type",
                "user_type_select": "Select...",
                "user_type_admin": "Administrator",
                "user_type_authority": "Environmental Authority",
                "user_type_common": "Common User",
                "menu_title": "Main Menu",
                "menu_subtitle": "Choose an option to get started:",
                "impactos": "Environmental Impacts",
                "problemas": "Environmental Issues",
                "tickets": "Tickets",
                "usuarios": "Users",
                "config": "Settings",
                "footer_quote": "I report the risk, the future I don't risk.",
                
                # Formulario Reporte Ambiental
                "register_report_title": "Environmental Report",
                "register_report_subtitle": "Help us protect the environment",
                "location_section": "Location",
                "localidad_label": "Locality",
                "barrio_label": "Neighborhood",
                "search_placeholder": "Type to search...",
                "select_placeholder": "Select...",
                "impact_section": "Impact Details",
                "categoria_label": "Environmental Category",
                "impacto_label": "Environmental Impact",
                "descripcion_label": "Description",
                "evidencia_section": "Evidence",
                "upload_placeholder": "Drag your image here or click to select",
                "upload_optional": "Optional",
                "register_report_button": "Register Ticket" ,
                "cancel_button": "Cancel",
                
                # Dashboards
                "dashboard_admin_title": "Administrator Panel",
                "dashboard_admin_subtitle": "From here you can manage users, review reports, and oversee the EcoRisk system.",
                "dashboard_admin_button1": "View Environmental Impacts",
                "dashboard_admin_button3": "View Reports",
                "dashboard_authority_title": "Environmental Authority Panel",
                "dashboard_authority_subtitle": "Review citizen reports, analyze impacts, and issue environmental resolutions.",
                "dashboard_authority_button1": "View Environmental Impacts",
                "dashboard_authority_button2": "Review Reports",
                "dashboard_authority_button3": "Issue Resolutions",
                "dashboard_greeting": "Hello,",
                "descripcion_admin": "Here you can manage users, review reports, and administer system settings.",
                "descripcion_autoridad": "Here you can review citizen reports, analyze environmental impacts, and issue resolutions.",
                
                # Modal View Reports
                "ticket_id": "Ticket ID",
                "ticket_descripcion": "Description",
                "ticket_fecha": "Creation Date",
                "ticket_categoria": "Category",
                "ticket_severidad": "Severity",
                "ticket_estado": "Status",
                "ticket_localidad": "Locality",
                "ticket_impacto": "Impact",
                "ticket_persona": "Person",
                "ticket_estado_tickets": "Ticket Status",
                "close_button": "Close",
            },

            # Francés
            "fr": {
                "home_title": "Bienvenue à Ecorisk",
                "home_subtitle": "La plateforme idéale pour évaluer, signaler et gérer les risques environnementaux.",
                "login_title": "Connexion",
                "login_user": "Nom d'utilisateur",
                "login_pass": "Mot de passe",
                "login_button": "Se Connecter",
                "register_link": "S'inscrire",
                "Without_account": "Vous n'avez pas de compte?",
                "register_title": "Inscription Utilisateur",
                "register_user": "Nom d'utilisateur",
                "register_email": "Courriel",
                "register_pass": "Mot de passe",
                "register_button": "S'inscrire",
                "login_link": "Se Connecter",
                "user_type_label": "Type d'utilisateur",
                "user_type_select": "Sélectionner...",
                "user_type_admin": "Administrateur",
                "user_type_authority": "Autorité Environnementale",
                "user_type_common": "Utilisateur Commun",
                "menu_title": "Menu Principal",
                "menu_subtitle": "Choisissez une option pour commencer :",
                "impactos": "Impacts Environnementaux",
                "problemas": "Problèmes Environnementaux",
                "tickets": "Tickets",
                "usuarios": "Utilisateurs",
                "config": "Paramètres",
                "footer_quote": "Je reporte le risque, l'avenir, je ne le risque pas.",
                
                # Formulario Reporte Ambiental
                "register_report_title": "Rapport Environnemental",
                "register_report_subtitle": "Aidez-nous à protéger l'environnement",
                "location_section": "Localisation",
                "localidad_label": "Localité",
                "barrio_label": "Quartier",
                "search_placeholder": "Tapez pour rechercher...",
                "select_placeholder": "Sélectionner...",
                "impact_section": "Détails de l'Impact",
                "categoria_label": "Catégorie Environnementale",
                "impacto_label": "Impact Environnemental",
                "descripcion_label": "Description",
                "evidencia_section": "Preuve",
                "upload_placeholder": "Glissez votre image ici ou cliquez pour sélectionner",
                "upload_optional": "Optionnel",
                "register_report_button": "Enregistrer le Ticket" ,
                "cancel_button": "Annuler",
                
                # Dashboards
                "dashboard_admin_title": "Panneau Administrateur",
                "dashboard_admin_subtitle": "Ici, vous pouvez gérer les utilisateurs, examiner les rapports et superviser le système EcoRisk.",
                "dashboard_admin_button1": "Voir les Impacts Environnementaux",
                "dashboard_admin_button3": "Voir les Rapports",
                "dashboard_authority_title": "Panneau de l'Autorité Environnementale",
                "dashboard_authority_subtitle": "Consultez les rapports citoyens, analysez les impacts et émettez des résolutions environnementales.",
                "dashboard_authority_button1": "Voir les Impacts Environnementaux",
                "dashboard_authority_button2": "Examiner les Rapports",
                "dashboard_authority_button3": "Émettre des Résolutions",
                "dashboard_greeting": "Bonjour,",
                "descripcion_admin": "Ici, vous pouvez gérer les utilisateurs, examiner les rapports et administrer les paramètres du système.",
                "descripcion_autoridad": "Ici, vous pouvez consulter les rapports citoyens, analyser les impacts environnementaux et émettre des résolutions.",
                
                # Modal Voir Rapports
                "ticket_id": "ID du Ticket",
                "ticket_descripcion": "Description",
                "ticket_fecha": "Date de Création",
                "ticket_categoria": "Catégorie",
                "ticket_severidad": "Gravité",
                "ticket_estado": "Statut",
                "ticket_localidad": "Localité",
                "ticket_impacto": "Impact",
                "ticket_persona": "Personne",
                "ticket_estado_tickets": "Statut Ticket",
                "close_button": "Fermer",
            }
        }

    def get_texts(self, lang="es"):
        return self.translations.get(lang, self.translations["es"]), lang
